# # Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
# source:
# - any: ['src/**/*', '!src/docs/*']
# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'test' label to any change to *.spec.js files within the source dir
modules:
- '/.mod'

# Add 'backend` label to any change to *.go files
backend:
- any: ['src/*.go']